subscribers:

  camera_reading:
    topic: /master/vehicle_node/dji_osdk_ros/main_camera_images
    queue_size: 1

actions:

  camera_reading:
    name: check_for_objects

publishers:

  object_detector:
    topic: found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: false
  wait_key_delay: 1
  enable_console_output: true
